# -*- coding: utf-8 -*-
"""Fashionmnist

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LtzYGR40pgQqaSEop_DykSReSegHO0l9
"""

import tensorflow as tf

fashion_mnist = tf.keras.datasets.fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0

x_train_4d = x_train.reshape(-1, 28, 28, 1)
x_test_4d = x_test.reshape(-1, 28, 28, 1)

cnn_model = tf.keras.models.Sequential([
                                        tf.keras.layers.Conv2D(32, (3, 3), activation = 'relu', input_shape = (28, 28, 1)),
                                        tf.keras.layers.MaxPooling2D((2, 2)),
                                        tf.keras.layers.Conv2D(64, (3, 3), activation = 'relu'),
                                        tf.keras.layers.MaxPooling2D((2, 2)),
                                        tf.keras.layers.Conv2D(64, (3, 3), activation = 'relu'),
                                        tf.keras.layers.Flatten(),
                                        tf.keras.layers.Dense(64, activation = 'relu'),
                                        tf.keras.layers.Dense(10, activation = 'softmax')])

cnn_model.compile(optimizer='adam', loss = 'sparse_categorical_crossentropy', metrics=['accuracy'])
cnn_model.fit(x_train_4d, y_train, epochs=5)

"""# 새 섹션"""

from google.colab import drive
drive.mount('/content/drive')

converter = tf.lite.TFLiteConverter.from_keras_model(cnn_model)
tflite_model = converter.convert()

with open('./keras_model_cnn.tflite', 'wb') as f:
  f.write(tflite_model)